# Generated by Django 4.1.2 on 2022-10-09 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='especialidade',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='medico',
            old_name='name',
            new_name='nome',
        ),
    ]
