# Generated by Django 4.1.2 on 2022-10-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='_esta_lotada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agendahorario',
            name='_esta_ocupado',
            field=models.BooleanField(default=False),
        ),
    ]
