# Generated by Django 4.1.2 on 2022-10-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicar', '0002_agenda__esta_lotada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='horario',
            field=models.TimeField(unique=True),
        ),
    ]
