# Generated by Django 4.1.2 on 2022-10-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicar', '0002_rename_name_especialidade_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='crm',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
