# Generated by Django 4.1.2 on 2022-10-10 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicar', '0005_alter_medico_crm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='especialidade',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='deleted_at',
        ),
    ]
